# Generated by Django 5.2.9 on 2025-12-31 12:22

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('path', models.CharField(help_text='URL or file path to the map (e.g. /media/maps/bus-network.pdf)', max_length=255)),
                ('preview_image', models.ImageField(blank=True, help_text='Optional PNG preview image', upload_to='maps/previews/')),
                ('hex_colour', models.CharField(help_text='Hex colour used for bar and outline (e.g. #0019A8)', max_length=7)),
                ('slug', models.SlugField(help_text='Used in map URLs', unique=True)),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Mode of transport',
                'verbose_name_plural': 'Modes of transport',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=50)),
                ('bustimes_slug', models.SlugField(help_text='Unique Bustimes.org operator slug', unique=True)),
                ('website', models.URLField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Telephone must be in +44 format', regex='^\\+44\\d{9,12}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo_circular', models.ImageField(blank=True, upload_to='operators/logos/circular/')),
                ('logo_banner', models.ImageField(blank=True, help_text='Only used on operator detail pages', upload_to='operators/logos/banner/')),
                ('primary_hex', models.CharField(help_text='Hex colour, e.g. #0019A8', max_length=7)),
                ('secondary_hex', models.CharField(blank=True, max_length=7)),
                ('has_custom_page', models.BooleanField(default=False, help_text='Enable a custom operator page layout')),
                ('custom_template', models.CharField(blank=True, help_text='Optional template path, e.g. siteui/operators/stagecoach.html', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Show this operator as featured on key pages')),
            ],
            options={
                'ordering': ['operator_name'],
            },
        ),
        migrations.CreateModel(
            name='ServiceStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
                ('colour_hex', models.CharField(help_text='TfL-approved hex colour (e.g. #DC241F)', max_length=7)),
            ],
            options={
                'verbose_name': 'Service status type',
                'verbose_name_plural': 'Service status types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Vehicle type',
                'verbose_name_plural': 'Vehicle types',
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteui.mode')),
            ],
            options={
                'verbose_name': 'Fare',
                'verbose_name_plural': 'Fares',
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service', models.CharField(help_text='e.g. X4, 1, 2, 3', max_length=10)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('via', models.CharField(blank=True, max_length=200)),
                ('route_group', models.CharField(blank=True, help_text='Optional grouping label', max_length=50)),
                ('route_hex', models.CharField(blank=True, help_text='Optional route-specific colour (e.g. #0019A8). If empty, operator colour is used.', max_length=7)),
                ('bustimes_id', models.IntegerField(help_text='Bustimes.org service ID', unique=True)),
                ('display_order', models.PositiveIntegerField(default=1000, help_text='Lower numbers appear first in lists')),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='siteui.mode')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='siteui.operator')),
                ('vehicles_used', models.ManyToManyField(blank=True, related_name='routes', to='siteui.vehicletype')),
            ],
            options={
                'unique_together': {('service', 'operator', 'mode')},
            },
        ),
        migrations.CreateModel(
            name='RouteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='Short headline message', max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Detailed public explanation')),
                ('affected_section', models.CharField(blank=True, help_text="e.g. 'Between Portsmouth & Fareham'", max_length=200)),
                ('is_planned', models.BooleanField(default=False, help_text='Planned works or closures')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='siteui.route')),
                ('status_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteui.servicestatustype')),
            ],
            options={
                'verbose_name': 'Route status',
                'verbose_name_plural': 'Route statuses',
                'ordering': ['-valid_from'],
            },
        ),
        migrations.AddField(
            model_name='operator',
            name='vehicles_operated',
            field=models.ManyToManyField(blank=True, to='siteui.vehicletype'),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Day Ticket, Weekly Pass', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Ticket price in GBP', max_digits=6)),
                ('duration', models.CharField(help_text='e.g. Day, Week, Month, Single journey', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='siteui.operator')),
            ],
            options={
                'ordering': ['operator', 'price'],
                'unique_together': {('name', 'operator')},
            },
        ),
    ]
