# Generated by Django 5.2.9 on 2025-12-30 17:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Mode of transport',
                'verbose_name_plural': 'Modes of transport',
            },
        ),
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Vehicle type',
                'verbose_name_plural': 'Vehicle types',
            },
        ),
        migrations.CreateModel(
            name='Fare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='siteui.mode')),
            ],
            options={
                'verbose_name': 'Fare',
                'verbose_name_plural': 'Fares',
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operator_name', models.CharField(max_length=20)),
                ('bustimes_slug', models.SlugField(help_text='Unique Bustimes.org operator slug', unique=True)),
                ('website', models.URLField(blank=True)),
                ('telephone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Telephone must be in +44 format', regex='^\\+44\\d{9,12}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('logo_circular', models.ImageField(blank=True, upload_to='operators/logos/circular/')),
                ('logo_banner', models.ImageField(blank=True, help_text='Only used on operator detail pages', upload_to='operators/logos/banner/')),
                ('primary_hex', models.CharField(help_text='Hex colour, e.g. #0019A8', max_length=7)),
                ('secondary_hex', models.CharField(blank=True, max_length=7)),
                ('vehicles_operated', models.ManyToManyField(blank=True, to='siteui.vehicletype')),
            ],
            options={
                'ordering': ['operator_name'],
            },
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('service', models.CharField(help_text='e.g. X4, 1, 2, 3', max_length=10)),
                ('origin', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('via', models.CharField(blank=True, max_length=200)),
                ('route_group', models.CharField(blank=True, help_text='Optional grouping label', max_length=50)),
                ('mode', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='siteui.mode')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='routes', to='siteui.operator')),
                ('vehicles_used', models.ManyToManyField(blank=True, related_name='routes', to='siteui.vehicletype')),
            ],
            options={
                'ordering': ['mode', 'service'],
                'unique_together': {('service', 'operator', 'mode')},
            },
        ),
    ]
