# Generated by Django 5.2.9 on 2025-12-30 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceStatusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Service status type',
                'verbose_name_plural': 'Service status types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RouteStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(help_text='Short headline message', max_length=200)),
                ('detail', models.TextField(blank=True, help_text='Detailed public explanation')),
                ('affected_section', models.CharField(blank=True, help_text="e.g. 'Between Portsmouth & Fareham'", max_length=200)),
                ('is_planned', models.BooleanField(default=False, help_text='Planned works or closures')),
                ('is_active', models.BooleanField(default=True)),
                ('valid_from', models.DateTimeField()),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='siteui.route')),
                ('status_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='siteui.servicestatustype')),
            ],
            options={
                'verbose_name': 'Route status',
                'verbose_name_plural': 'Route statuses',
                'ordering': ['-valid_from'],
            },
        ),
    ]
