# Generated by Django 5.2.9 on 2025-12-31 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatustype',
            name='severity',
            field=models.PositiveSmallIntegerField(default=0, help_text='Lower = better service'),
        ),
    ]
