# Generated by Django 5.2.9 on 2025-12-30 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0002_servicestatustype_routestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicestatustype',
            name='colour_hex',
            field=models.CharField(default=1, help_text='TfL-approved hex colour (e.g. #DC241F)', max_length=7),
            preserve_default=False,
        ),
    ]
