# Generated by Django 5.2.9 on 2025-12-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0003_servicestatustype_colour_hex'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_hex',
            field=models.CharField(blank=True, help_text='Optional route-specific colour (e.g. #0019A8). If empty, operator colour is used.', max_length=7),
        ),
    ]
