# Generated by Django 5.2.9 on 2025-12-31 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0003_add_tfl_statuses'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkIncident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_time', models.DateTimeField()),
                ('expected_end_time', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('affects_modes', models.ManyToManyField(blank=True, help_text='If empty, affects entire network', to='siteui.mode')),
                ('status_type', models.ForeignKey(help_text='Overall impact (e.g. Severe Delays)', on_delete=django.db.models.deletion.PROTECT, to='siteui.servicestatustype')),
            ],
        ),
    ]
