# Generated by Django 5.2.9 on 2025-12-30 18:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0004_route_route_hex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='e.g. Day Ticket, Weekly Pass', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Ticket price in GBP', max_digits=6)),
                ('duration', models.CharField(help_text='e.g. Day, Week, Month, Single journey', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='siteui.operator')),
            ],
            options={
                'ordering': ['operator', 'price'],
                'unique_together': {('name', 'operator')},
            },
        ),
    ]
