# Generated by Django 5.2.9 on 2025-12-30 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0005_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('path', models.CharField(help_text='URL or file path to the map (e.g. /media/maps/bus-network.pdf)', max_length=255)),
                ('hex_colour', models.CharField(help_text='Hex colour used for bar and outline (e.g. #0019A8)', max_length=7)),
            ],
            options={
                'verbose_name': 'Map',
                'verbose_name_plural': 'Maps',
                'ordering': ['title'],
            },
        ),
    ]
