# Generated by Django 5.2.9 on 2025-12-30 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0006_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='preview_image',
            field=models.ImageField(blank=True, help_text='Optional PNG preview image', upload_to='maps/previews/'),
        ),
    ]
