# Generated by Django 5.2.9 on 2025-12-30 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0007_map_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='custom_template',
            field=models.CharField(blank=True, help_text='Optional template path, e.g. siteui/operators/stagecoach.html', max_length=100),
        ),
        migrations.AddField(
            model_name='operator',
            name='has_custom_page',
            field=models.BooleanField(default=False, help_text='Enable a custom operator page layout'),
        ),
    ]
