# Generated by Django 5.2.9 on 2025-12-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0008_operator_custom_template_operator_has_custom_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='slug',
            field=models.SlugField(default=1, help_text='Used in map URLs', unique=True),
            preserve_default=False,
        ),
    ]
