# Generated by Django 5.2.9 on 2025-12-30 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0009_map_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='bustimes_id',
            field=models.IntegerField(default=1, help_text='Bustimes.org service ID', unique=True),
            preserve_default=False,
        ),
    ]
