# Generated by Django 5.2.9 on 2025-12-30 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0010_route_bustimes_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='display_order',
            field=models.PositiveIntegerField(default=1000, help_text='Lower numbers appear first in lists'),
        ),
    ]
