# Generated by Django 5.2.9 on 2025-12-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0011_route_display_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='route',
            options={},
        ),
        migrations.AlterField(
            model_name='operator',
            name='operator_name',
            field=models.CharField(max_length=50),
        ),
    ]
