# Generated by Django 5.2.9 on 2025-12-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0013_remove_route_unique_constraint'),
    ]

    operations = [
        migrations.AddField(
            model_name='operator',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together={('service', 'operator', 'mode')},
        ),
    ]
