# Generated by Django 5.2.9 on 2025-12-30 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0014_operator_slug_alter_route_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=False),
        ),
    ]
