# Generated by Django 5.2.9 on 2025-12-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0015_alter_operator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='slug',
            field=models.SlugField(default=1, help_text='Unique URL slug for the operator', unique=False),
            preserve_default=False,
        ),
    ]
