# Generated by Django 5.2.9 on 2025-12-30 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteui', '0016_alter_operator_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operator',
            name='slug',
            field=models.SlugField(help_text='Unique URL slug for the operator'),
        ),
    ]
